---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "rewrite"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "all"
